version: "3.9"

services:
  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

  mongo-client:
    image: mongo-express:latest
    container_name: mongo-client
    restart: always
    depends_on:
      - mongo-server
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-server
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    networks:
      - mongodb_network

  nats-server:
    image: nats:alpine3.21
    container_name: nats-server
    restart: always
    ports:
      - "4222:4222"   # Puerto cliente
      - "8222:8222"   # Puerto de monitoreo HTTP
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    command: ["-c", "/etc/nats/nats.conf"]

volumes:
  mongodb_data:

networks:
  mongodb_network: